trigger:
 branches:
   include:
    - main

pool: GMPool

stages:
 - stage: build
   displayName: build stage
   jobs:
    - job: terraformplan
      displayName: terraform plan
      steps:
      - task: TerraformInstaller@1
        displayName: terffaorm install
        inputs:
          terraformVersion: 'latest'